identifier: notifications-service
title: Notifications Service
blueprint: service
properties:
  language: nodejs
  tier: tier1
  readme: .readme
  freshness: .freshness
relations:
  owner: team-checkout
